version: '3'

services: 
    db:
        image: postgres:12.0-alpine
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=atlan_collect
    
    web:
        build: ./project
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports: 
            - "8000:8000"
        depends_on: 
            - db
            - redis
    
    redis:
        image: redis:alpine
        ports: 
            - "6379:6379"
    
    celery:
        build: ./project
        command: celery worker -A taskmanager -l info
        depends_on: 
            - web
      
